name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Dir x86
        run: dir "c:\Program Files (x86)\"

      - name: Dir x64
        run: dir c:\Program Files\
